services:
  nginx:
    container_name: css-miniprojects
    image: nginx:stable-alpine3.17-slim
    ports:
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - websocket
  wsserver:
    container_name: hotreload-server
    build: .
    volumes:
      - ./src:/opt/html:ro
    networks:
      - websocket
networks:
  websocket:
    driver: bridge
